# Generated by Django 5.2.12 on 2026-03-04 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g., from Unsplash)', null=True),
        ),
    ]
